version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    restart: unless-stopped

  ist-site:
    image: ghcr.io/navatusein/ist-site:dev-latest
    container_name: ist-site
    ports:
      - 80:80
    volumes:
      - ist-public-files:/app/public/files
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb/${MONGODB_DATABASE}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}
      - APP_SECRET=${APP_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: unless-stopped

volumes:
  mongodb-data:
  ist-public-files: